---

- name: create folders
  file:
    state: directory
    mode: 0755
    recurse: no
    path: "{{ item }}"
  with_items:
  - /etc/php71
  - /etc/php71/fpm
  - /etc/php71/fpm/conf.d
  - /etc/php71/fpm/pool.d
  - /var/www
  - /var/log/php7-fpm
  become: yes

- name: Create log folder
  file: state=directory mode=0755 recurse=yes path={{ php7fpm_error_log | dirname }}
  when: php7fpm_error_log is defined
  become: yes

- name: Create php.ini
  template: src=php.ini dest=/etc/php71/fpm/php.ini mode=0644
  become: yes
  notify: restart_php7_fpm

- name: Add logrotate config
  copy: src=logrotate dest=/etc/logrotate.d/php71-fpm mode=0644
  become: yes
  notify: restart_php7_fpm

- name: Add fpm config
  template: src=php-fpm.conf dest=/etc/php71/fpm/fpm.conf
  become: yes
  notify: restart_php7_fpm

- name: Add default fpm pool
  copy: src=default.conf dest=/etc/php71/fpm/pool.d/default.conf
  become: yes
  notify: restart_php7_fpm

- name: Check for systemd
  command: systemctl --version
  register: systemctl_version
  ignore_errors: yes

- name: Add php-fpm.service
  copy: src=php-fpm.service.conf dest=/lib/systemd/system/php71-fpm.service mode=0644
  become: yes
  when: systemctl_version.rc == 0
  notify: restart_php7_fpm

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemctl_version.rc == 0
  become: yes

- name: Add php-fpm.init
  copy: src=php-fpm.init.conf dest=/etc/init.d/php71-fpm mode="a+x"
  become: yes
  when: systemctl_version.rc != 0
  notify: restart_php7_fpm
